version: '3'

services:

  melchior.local.com:
    container_name: melchior_python
    build:
      context: .
      dockerfile: app/Dockerfile
    image: python_blog
    volumes:
      - .:/app
      - ./static/admin:/static/admin
    ports:
      - "38001:80"
    command: python /app/app/manage.py runserver 0.0.0.0:80

networks:
  frontend_network:
    driver: bridge

volumes:
  static_volume: null
