version: '3'

services:

  db:
    image: mariadb:11.4.2
    container_name: melchior_mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: melchior
      MYSQL_ROOT_USER: melchior_user
      MYSQL_ROOT_PASSWORD: rX@5#98nGR09
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 192.168.10.10

  backend:
    container_name: melchior_backend
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
      - ./static/admin:/static/admin
    expose:
      - "8001"
    ports:
      - "8001:8001"
    command: python /app/app/manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 192.168.10.11

  frontend:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./frontend/web-front:/home/app/frontend
    ports:
      - 3000:3000
    working_dir: /home/app/frontend
    networks:
      default:
        ipv4_address: 192.168.10.12

  nginx:
    container_name: melchior_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - backend
    depends_on:
      - backend
      - frontend
    networks:
      default:
        ipv4_address: 192.168.10.13

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  static_volume: null
