version: '3'

services:

  db:
    image: mariadb:10.1
    container_name: melchior_mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: melchior
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d

  python:
    container_name: melchior_python
    build:
      context: .
      dockerfile: app/Dockerfile
    image: python_blog
    volumes:
      - .:/app
      - ./static/admin:/static/admin
    expose:
      - "8001"
    ports:
      - "8001:8001"
    command: /bin/sh /app/start_python.sh
    depends_on:
      - db

  web-front:
    image: node:16.13.1
    volumes:
      - ./frontend/web-front:/home/app/frontend
    ports:
      - 3000:3000
    working_dir: /home/app/frontend
    command:
      [
        bash,
        -c,
        yarn upgrade --no-progress --network-timeout 1000000 && yarn run dev
      ]
    networks:
      - frontend_network

  frontend-server:
    container_name: nginx_frontend
    build:
      context: ./frontend/nginx/.
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - web-front
    networks:
      - frontend_network

  nginx:
    image: nginx:1.17.9
    container_name: melchior_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/var/www/static
      - ./nginx/log:/var/log/nginx
      - ./dist:/var/www/dist
    depends_on:
      - python

networks:
  frontend_network:
    driver: bridge
volumes:
  static_volume: null
