version: '3'

services:

  db:
    image: mariadb:11.2.4
    container_name: melchior-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: melchior
      MYSQL_ROOT_USER: melchior_user
      MYSQL_ROOT_PASSWORD: rX@5#98nGR09
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    user: 999:999
    networks:
      default:
        ipv4_address: 192.168.10.10

  backend:
    container_name: melchior-backend
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
      - ./static/admin:/static/admin
    expose:
      - "8001"
    ports:
      - "8001:8001"
    command: /bin/sh /app/docker/django/start_python.sh
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 192.168.10.11

  frontend:
    container_name: melchior-frontend
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./frontend/web-front:/home/app/frontend
    ports:
      - 3000:3000
    working_dir: /home/app/frontend
    networks:
      default:
        ipv4_address: 192.168.10.12

  nginx:
    container_name: melchior-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/uwsgi:/var/run/uwsgi
    volumes_from:
      - backend
    depends_on:
      - backend
      - frontend
    networks:
      default:
        ipv4_address: 192.168.10.13

networks:
  default:
    ipam:
      driver: bridge
      config:
        - subnet: 192.168.10.0/24

volumes:
  static_volume: null
