CREATE DATABASE IF NOT EXISTS melchior CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON melchior.* TO 'root'@'%';

FLUSH PRIVILEGES;