# Generated by Django 3.0.3 on 2020-04-29 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.BigIntegerField(default=0, verbose_name='serial_number')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='初回作成日')),
                ('created_by', models.CharField(default='', max_length=50, verbose_name='初回作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('updated_by', models.CharField(default='', max_length=50, verbose_name='最終更新者')),
                ('status', models.IntegerField(default=0, verbose_name='状態')),
                ('company_id', models.CharField(default='', max_length=50, verbose_name='会社ID')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.BigIntegerField(default=0, verbose_name='serial_number')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='初回作成日')),
                ('created_by', models.CharField(default='', max_length=50, verbose_name='初回作成者')),
                ('company_id', models.CharField(default='', max_length=50, verbose_name='会社ID')),
                ('name', models.CharField(default='', max_length=254, verbose_name='名称')),
                ('post_code', models.CharField(default='', max_length=20, verbose_name='郵便番号')),
                ('address1', models.CharField(default='', max_length=254, verbose_name='住所1')),
                ('address2', models.CharField(default='', max_length=254, verbose_name='住所2')),
                ('tel_no', models.CharField(default='', max_length=20, verbose_name='電話番号')),
                ('email_address1', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス1')),
                ('email_address2', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス2')),
                ('homepage_url', models.URLField(verbose_name='ホームページ')),
                ('founded_at', models.CharField(default='', max_length=20, verbose_name='創立日')),
                ('president', models.CharField(default='', max_length=50, verbose_name='代表者')),
                ('summary', models.CharField(default='', max_length=200, verbose_name='概要')),
                ('description', models.CharField(default='', max_length=4000, verbose_name='詳細')),
                ('market_code', models.CharField(default='', max_length=50, verbose_name='市場コード')),
                ('stock_code', models.CharField(default='', max_length=50, verbose_name='銘柄コード')),
            ],
            options={
                'db_table': 'company_logs',
            },
        ),
    ]
